# Generated by Django 5.0.6 on 2024-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chatgpt", "0003_delete_chromadata_delete_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
