# Generated by Django 5.0.6 on 2024-06-11 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0005_helpaivleqa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Helpaivleqa",
        ),
    ]
