# Generated by Django 5.0.6 on 2024-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatgptHelpaivleqa",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("pclass", models.TextField()),
                ("qa", models.TextField()),
            ],
            options={
                "db_table": "chatgpt_helpaivleQA",
                "managed": False,
            },
        ),
    ]
