# Generated by Django 5.0.6 on 2024-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatgpt", "0003_chathistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="conversation_id",
            field=models.CharField(default="default_value", max_length=36),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="chat_message",
        ),
    ]
